version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      xyz: abc
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=sysfoo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
